// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
  "/communities": {
    params: {};
  };
  "/communities/:id": {
    params: {
      "id": string;
    };
  };
  "/categories": {
    params: {};
  };
  "/posts": {
    params: {};
  };
  "/posts/:id": {
    params: {
      "id": string;
    };
  };
  "/comments": {
    params: {};
  };
  "/flagged": {
    params: {};
  };
  "/flagged/:id": {
    params: {
      "id": string;
    };
  };
  "/export": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/users" | "/users/:id" | "/communities" | "/communities/:id" | "/categories" | "/posts" | "/posts/:id" | "/comments" | "/flagged" | "/flagged/:id" | "/export" | "/profile" | "/login" | "/*";
  };
  "pages/admin/layout.tsx": {
    id: "pages/admin/layout";
    page: "/" | "/users" | "/users/:id" | "/communities" | "/communities/:id" | "/categories" | "/posts" | "/posts/:id" | "/comments" | "/flagged" | "/flagged/:id" | "/export" | "/profile";
  };
  "pages/AdminDashboardPage.tsx": {
    id: "pages/AdminDashboardPage";
    page: "/";
  };
  "pages/AdminUsersPage.tsx": {
    id: "pages/AdminUsersPage";
    page: "/users";
  };
  "pages/AdminUserDetailPage.tsx": {
    id: "pages/AdminUserDetailPage";
    page: "/users/:id";
  };
  "pages/AdminCommunitiesPage.tsx": {
    id: "pages/AdminCommunitiesPage";
    page: "/communities";
  };
  "pages/AdminCommunityDetailPage.tsx": {
    id: "pages/AdminCommunityDetailPage";
    page: "/communities/:id";
  };
  "pages/AdminCategoriesPage.tsx": {
    id: "pages/AdminCategoriesPage";
    page: "/categories";
  };
  "pages/AdminPostsPage.tsx": {
    id: "pages/AdminPostsPage";
    page: "/posts";
  };
  "pages/AdminPostDetailPage.tsx": {
    id: "pages/AdminPostDetailPage";
    page: "/posts/:id";
  };
  "pages/AdminCommentsPage.tsx": {
    id: "pages/AdminCommentsPage";
    page: "/comments";
  };
  "pages/AdminFlaggedPage.tsx": {
    id: "pages/AdminFlaggedPage";
    page: "/flagged";
  };
  "pages/AdminFlagDetailPage.tsx": {
    id: "pages/AdminFlagDetailPage";
    page: "/flagged/:id";
  };
  "pages/AdminExportPage.tsx": {
    id: "pages/AdminExportPage";
    page: "/export";
  };
  "pages/AdminProfilePage.tsx": {
    id: "pages/AdminProfilePage";
    page: "/profile";
  };
  "pages/AdminLoginPage.tsx": {
    id: "pages/AdminLoginPage";
    page: "/login";
  };
  "pages/AdminNotFoundPage.tsx": {
    id: "pages/AdminNotFoundPage";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/admin/layout": typeof import("./app/pages/admin/layout.tsx");
  "pages/AdminDashboardPage": typeof import("./app/pages/AdminDashboardPage.tsx");
  "pages/AdminUsersPage": typeof import("./app/pages/AdminUsersPage.tsx");
  "pages/AdminUserDetailPage": typeof import("./app/pages/AdminUserDetailPage.tsx");
  "pages/AdminCommunitiesPage": typeof import("./app/pages/AdminCommunitiesPage.tsx");
  "pages/AdminCommunityDetailPage": typeof import("./app/pages/AdminCommunityDetailPage.tsx");
  "pages/AdminCategoriesPage": typeof import("./app/pages/AdminCategoriesPage.tsx");
  "pages/AdminPostsPage": typeof import("./app/pages/AdminPostsPage.tsx");
  "pages/AdminPostDetailPage": typeof import("./app/pages/AdminPostDetailPage.tsx");
  "pages/AdminCommentsPage": typeof import("./app/pages/AdminCommentsPage.tsx");
  "pages/AdminFlaggedPage": typeof import("./app/pages/AdminFlaggedPage.tsx");
  "pages/AdminFlagDetailPage": typeof import("./app/pages/AdminFlagDetailPage.tsx");
  "pages/AdminExportPage": typeof import("./app/pages/AdminExportPage.tsx");
  "pages/AdminProfilePage": typeof import("./app/pages/AdminProfilePage.tsx");
  "pages/AdminLoginPage": typeof import("./app/pages/AdminLoginPage.tsx");
  "pages/AdminNotFoundPage": typeof import("./app/pages/AdminNotFoundPage.tsx");
};