// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/feed": {
    params: {};
  };
  "/posts/:id": {
    params: {
      "id": string;
    };
  };
  "/posts/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/communities": {
    params: {};
  };
  "/communities/:id": {
    params: {
      "id": string;
    };
  };
  "/communities/:id/create-post": {
    params: {
      "id": string;
    };
  };
  "/communities/:id/post": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/profile/following": {
    params: {};
  };
  "/profile/followers": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/forgot-password" | "/reset-password" | "/home" | "/feed" | "/posts/:id" | "/posts/:id/edit" | "/communities" | "/communities/:id" | "/communities/:id/create-post" | "/communities/:id/post" | "/profile" | "/profile/edit" | "/profile/following" | "/profile/followers" | "/users/:id" | "/settings" | "/notifications" | "/*";
  };
  "pages/SplashPage.tsx": {
    id: "pages/SplashPage";
    page: "/";
  };
  "pages/auth/layout.tsx": {
    id: "pages/auth/layout";
    page: "/login" | "/signup" | "/forgot-password" | "/reset-password";
  };
  "pages/LoginPage.tsx": {
    id: "pages/LoginPage";
    page: "/login";
  };
  "pages/SignupPage.tsx": {
    id: "pages/SignupPage";
    page: "/signup";
  };
  "pages/ForgotPasswordPage.tsx": {
    id: "pages/ForgotPasswordPage";
    page: "/forgot-password";
  };
  "pages/ResetPasswordPage.tsx": {
    id: "pages/ResetPasswordPage";
    page: "/reset-password";
  };
  "pages/app/layout.tsx": {
    id: "pages/app/layout";
    page: "/home" | "/feed" | "/posts/:id" | "/posts/:id/edit" | "/communities" | "/communities/:id" | "/communities/:id/create-post" | "/communities/:id/post" | "/profile" | "/profile/edit" | "/profile/following" | "/profile/followers" | "/users/:id" | "/settings" | "/notifications";
  };
  "pages/app/layout-sidebar.tsx": {
    id: "pages/app/layout-sidebar";
    page: "/home" | "/feed";
  };
  "pages/FeedPage.tsx": {
    id: "home";
    page: "/home";
  } | {
    id: "feed";
    page: "/feed";
  };
  "pages/app/layout-main.tsx": {
    id: "pages/app/layout-main";
    page: "/posts/:id" | "/posts/:id/edit" | "/communities" | "/communities/:id" | "/communities/:id/create-post" | "/communities/:id/post" | "/profile" | "/profile/edit" | "/profile/following" | "/profile/followers" | "/users/:id" | "/settings" | "/notifications";
  };
  "pages/PostDetailPage.tsx": {
    id: "pages/PostDetailPage";
    page: "/posts/:id";
  };
  "pages/EditPostPage.tsx": {
    id: "pages/EditPostPage";
    page: "/posts/:id/edit";
  };
  "pages/CommunitiesPage.tsx": {
    id: "pages/CommunitiesPage";
    page: "/communities";
  };
  "pages/CommunityDetailPage.tsx": {
    id: "pages/CommunityDetailPage";
    page: "/communities/:id";
  };
  "pages/CreatePostPage.tsx": {
    id: "create-post";
    page: "/communities/:id/create-post";
  } | {
    id: "community-post";
    page: "/communities/:id/post";
  };
  "pages/ProfilePage.tsx": {
    id: "pages/ProfilePage";
    page: "/profile";
  };
  "pages/EditProfilePage.tsx": {
    id: "pages/EditProfilePage";
    page: "/profile/edit";
  };
  "pages/FollowingPage.tsx": {
    id: "pages/FollowingPage";
    page: "/profile/following";
  };
  "pages/FollowersPage.tsx": {
    id: "pages/FollowersPage";
    page: "/profile/followers";
  };
  "pages/UserProfilePage.tsx": {
    id: "pages/UserProfilePage";
    page: "/users/:id";
  };
  "pages/SettingsPage.tsx": {
    id: "pages/SettingsPage";
    page: "/settings";
  };
  "pages/NotificationsPage.tsx": {
    id: "pages/NotificationsPage";
    page: "/notifications";
  };
  "pages/NotFoundPage.tsx": {
    id: "pages/NotFoundPage";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/SplashPage": typeof import("./app/pages/SplashPage.tsx");
  "pages/auth/layout": typeof import("./app/pages/auth/layout.tsx");
  "pages/LoginPage": typeof import("./app/pages/LoginPage.tsx");
  "pages/SignupPage": typeof import("./app/pages/SignupPage.tsx");
  "pages/ForgotPasswordPage": typeof import("./app/pages/ForgotPasswordPage.tsx");
  "pages/ResetPasswordPage": typeof import("./app/pages/ResetPasswordPage.tsx");
  "pages/app/layout": typeof import("./app/pages/app/layout.tsx");
  "pages/app/layout-sidebar": typeof import("./app/pages/app/layout-sidebar.tsx");
  "home": typeof import("./app/pages/FeedPage.tsx");
  "feed": typeof import("./app/pages/FeedPage.tsx");
  "pages/app/layout-main": typeof import("./app/pages/app/layout-main.tsx");
  "pages/PostDetailPage": typeof import("./app/pages/PostDetailPage.tsx");
  "pages/EditPostPage": typeof import("./app/pages/EditPostPage.tsx");
  "pages/CommunitiesPage": typeof import("./app/pages/CommunitiesPage.tsx");
  "pages/CommunityDetailPage": typeof import("./app/pages/CommunityDetailPage.tsx");
  "create-post": typeof import("./app/pages/CreatePostPage.tsx");
  "community-post": typeof import("./app/pages/CreatePostPage.tsx");
  "pages/ProfilePage": typeof import("./app/pages/ProfilePage.tsx");
  "pages/EditProfilePage": typeof import("./app/pages/EditProfilePage.tsx");
  "pages/FollowingPage": typeof import("./app/pages/FollowingPage.tsx");
  "pages/FollowersPage": typeof import("./app/pages/FollowersPage.tsx");
  "pages/UserProfilePage": typeof import("./app/pages/UserProfilePage.tsx");
  "pages/SettingsPage": typeof import("./app/pages/SettingsPage.tsx");
  "pages/NotificationsPage": typeof import("./app/pages/NotificationsPage.tsx");
  "pages/NotFoundPage": typeof import("./app/pages/NotFoundPage.tsx");
};